{{- if .Values.ingress.useTLS }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name | default "ideavault-prod" }}
spec:
  acme:
    server: {{ .Values.clusterIssuer.server | default "https://acme-v02.api.letsencrypt.org/directory" | quote }}
    email: {{ .Values.clusterIssuer.email | quote }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecretName | default "ideavault-tls-secret" | quote }}
    solvers:
    - http01:
        ingress:
          class: {{ .Values.clusterIssuer.ingressClass | default "nginx" | quote }}
{{- end }}