apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ideavault.fullname" . }}
  labels:
      {{- with .Values.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }} 
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  template:
    metadata:
      labels:
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            {{- if .Values.image.env }}
            {{- toYaml .Values.image.env | nindent 12 }}
            {{- end }}
          ports:
            - containerPort: 5000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}


