apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: idea-app-met
      port: {{ .Values.service.port }}
  selector:
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
